### ISSUE TITLE
Install & use

### ISSUE THREAD

**Issue by addictif80** [sergix44/hestiacp-companion#3]
Hello,
after few days for reverse proxy deployment, i've found your hestiacp-companion, but idk how to use it.
Can you explain and/or make a documentation ?
Best regards :)

**Comment by sergix44** [comment]
For the reverse proxy, you need to run the command to install the additional templates
`php ./hcpc reverse-proxy`
Then simply go to the hestiacp page, in the domain you want, and in the settings, put the reverse proxy url in the Proxy Extension field

**Comment by addictif80** [comment]
After installing hcpc file, in HestiaCP domain config, i've selected http_reverse_proxy but i've no "Proxy Extension" field. Same for https_reverse_proxy and unix_reverse_proxy.
![image](https://github.com/user-attachments/assets/d94a7424-06e1-42d3-a532-f583918e62c4)

**Comment by epsilonion-liam** [comment]
Can you add ports to the IP address?
example: <IP_address>:<port> or 192.168.0.1:8100

So you are redirected to ip address and port when URL is entered in browser?


Thank you sooo much for this, people have been asking for this feature for many years.

**Comment by addictif80** [comment]
> Can you add ports to the IP address? example: <IP_address>: or 192.168.0.1:8100
> 
> So you are redirected to ip address and port when URL is entered in browser?
> 
> Thank you sooo much for this, people have been asking for this feature for many years.

Yes, it's a transparent redirection
When you setup sub.domain.com with reverse proxy to emby (exemple) on 192.168.0.100:5050, sub.domain.com show your emby install, but you are not redirected to thé IP adresse (it have no sense because visitors are unable to accessing your local network)

**Comment by sergix44** [comment]
> Can you add ports to the IP address? example: <IP_address>: or 192.168.0.1:8100
> 
> So you are redirected to ip address and port when URL is entered in browser?
> 
> Thank you sooo much for this, people have been asking for this feature for many years.

You can proxy whatever ip:port you want, like this
![immagine](https://github.com/user-attachments/assets/d3e2299a-e1e8-4c2a-8faa-949e5975c855)
